### ISSUE TITLE
look into making pbsdsh default bootstrap server for recent Intel MPI

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-mympirun#82]
advantages:
- doesn't require passwordless SSH to work (cfr. #74)
- NUMA-aware placement of remote processes via Torque

example (with Intel MPI)

```
mpirun -bootstrap pbsdsh -np 40 ./mpi_helloworld
```

**Comment by boegel** [comment]
should actually use the `pbsssh` wrapper (see `bin/pbsssh.sh`)

**Comment by boegel** [comment]
relevant documentation:

https://www.vscentrum.be/cluster-doc/running-jobs/starting-programs-in-job#starting-a-single-core-program-on-each-assigned-core

http://docs.adaptivecomputing.com/torque/6-0-1/help.htm#topics/torque/commands/pbsdsh.htm

**Comment by Caylo** [comment]
the problem seems to be mostly the if/else under this:
https://github.com/hpcugent/vsc-mympirun/blob/develop/lib/vsc/mympirun/mpi/mpi.py#L820 where `-rmk` is prioritized over the launcher, which shouldn't happen. 
(more info on that:
    - http://www.failureasaservice.com/2014/04/mpich-and-mvapich-with-torque.html
    - https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/278096)

`HYDRA_LAUNCHER_NAME` and `HYDRA_LAUNCHER_EXEC` are hardcoded into the schedulers, we should look into making this an option e.g. `--launcher

also, the `mympisanity`script needs some reviewing (see https://github.com/hpcugent/vsc-mympirun/issues/80) so we can use it to debug/sanity check how processes are pinned

**Comment by boegel** [comment]
see #110

**Comment by boegel** [comment]
#110 is merged, but not perfect, see #114

**Comment by Caylo** [comment]
#114 fixed in #115
